services:
  - type: web
    name: my-vite-app
    env: node
    plan: free
    buildCommand: npm install && npm run build --mode production
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
