import dayjs from "dayjs";

export const filedContainers = [
    { key: "bookingInfo", title: "Booking Details", id: "bookingDetails" },
    { key: "income", title: "Income Details", id: "amountDetails" },
    { key: "accountInfo", title: "Account Details", id: "accountDetails" },
    {
        key: "calculation",
        title: "Calculation Details",
        id: "calculationDetails",
    },
];

export const incomeFields = {
    bookingDetails: [
        {
            name: "Tenant Name",
            type: "text",
            container: "bookingDetails",
            apiKey: "tenant_name",
            isRequired: true,
        },
        {
            name: "Stay Name",
            type: "dropDown",
            container: "bookingDetails",
            apiKey: "stay_name",
            isRequired: true,
        },
        {
            name: "Room No",
            type: "dropDown",
            container: "bookingDetails",
            apiKey: "room_no",
            isRequired: true,
        },
        {
            name: "Date Of Booking",
            type: "dateRangePicker",
            container: "bookingDetails",
            apiKey: "date_of_booking",
            isRequired: true,
        },
        {
            name: "Booking From",
            type: "dropDown",
            options: [],
            container: "bookingDetails",
            apiKey: "booking_from",
            isRequired: true,
        },
        {
            name: "GST Transction",
            type: "radio",
            value: true,
            container: "calculationDetails",
            apiKey: "gst_transction",
            isRequired: true,
        },
    ],
    amountDetails: [
        {
            name: "Total Without Taxes",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "total_without_taxes",
            isRequired: true,
        },
        {
            name: "Tax Slab (%)",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "tax_slab",
            isRequired: true,
        },
        {
            name: "Total Tax Amount (GST)",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "balance_amount",
            isRequired: true,
            isDisabledPermanently: true,
        },
        {
            name: "Total with Taxes and Fees",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "extra_amount",
            isRequired: true,
            isDisabledPermanently: true,
        },
        {
            name: "Commission amount",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "commission_amount",
            isRequired: true,
            isDisabledPermanently: true,
        },
        {
            name: "Commission amount - GST (inward)",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "commission_amount_gst",
            isRequired: true,
            isDisabledPermanently: true,
        },
        {
            name: "TCS (0.1%)",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "tcs_amount",
            isRequired: true,
            isDisabledPermanently: true,
        },
        {
            name: "TDS (0.5%)",
            type: "number",
            value: 0,
            container: "amountDetails",
            apiKey: "tds_amount",
            isRequired: true,
            isDisabledPermanently: true,
        },
    ],
    accountDetails: [
        {
            name: "Amount Received in Cash",
            type: "number",
            value: 0,
            container: "accountDetails",
            apiKey: "cash_received",
            isRequired: false,
            calculateTotal: true,
        },
        {
            name: "Amount Received in Gpay",
            type: "number",
            value: 0,
            container: "accountDetails",
            apiKey: "amount_received_in_gpay",
            isRequired: false,
            calculateTotal: true,
        },
        {
            name: "Amount Received in Account",
            type: "number",
            value: 0,
            container: "accountDetails",
            apiKey: "amount_received_in_account",
            isRequired: false,
            calculateTotal: true,
        },
        {
            name: "Amount Credited to",
            type: "multidropDown",
            value: null,
            container: "accountDetails",
            apiKey: "amount_credited_to",
            isRequired: true,
        },
    ],
    calculationDetails: [
        {
            name: "Profit",
            type: "text",
            value: 0,
            disabled: true,
            container: "calculationDetails",
            apiKey: "final_amount",
            isDisabledPermanently: true,
            calculateTotal: true,
        },
    ],
};

export const expenseContainer = [{ key: "expense", title: "Expense Details" }];

export const expenseFileds = [
    {
        name: "Date Of Expense",
        type: "datePicker",
        value: null,
        container: "expense",
        apiKey: "expense_date",
        isRequired: true,
    },
    {
        name: "Expense for",
        type: "dropDown",
        value: null,
        container: "expense",
        apiKey: "expense_for",
        isRequired: true,
    },
    {
        name: "Expenses Explanation",
        type: "text",
        value: "",
        container: "expense",
        apiKey: "expenses_explanation",
        isRequired: true,
    },
    {
        name: "GST Transction (Expense)",
        type: "radio",
        value: true,
        container: "calculationDetails",
        apiKey: "gst_transction_expense",
        isRequired: true,
    },
    {
        name: "Inward GST Amount",
        type: "number",
        container: "calculationDetails",
        apiKey: "gst_amount_inward",
        isRequired: true,
    },
    {
        name: "Amount Debited from",
        type: "dropDown",
        value: null,
        container: "expense",
        apiKey: "amount_debited_from",
        isRequired: true,
    },
    {
        name: "Total Expense",
        type: "number",
        value: 0,
        container: "expenses",
        apiKey: "total_expense",
        isRequired: true,
        calculateTotal: true,
        rules: [{ min: 1, type: "number", message: `Expenses cannot be 0` }],
    },
];

export const fields = [
    {
        name: "Type",
        apiKey: "isIncome",
    },
    ...incomeFields.bookingDetails,
    ...incomeFields.amountDetails,
    ...incomeFields.accountDetails,
    ...incomeFields.calculationDetails,
    ...expenseFileds,
    {
        name: "Profit / Loss Amount",
        apiKey: "profit_loss",
        calculateTotal: true,
    },
];

export const resetAccountDetails = [];
